seed_app/urls.py
from django.urls import path
from . import views

app_name = 'seed_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('seedinfo/', views.seedinfo, name='seedinfo'),
    path('gallery/', views.gallery, name='gallery'),
    path('aboutus/', views.aboutus, name='aboutus'),
]

seedqt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('seed_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seed_app/models.py
from django.db import models

# Create your models here.

seed_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from PIL import Image
from keras.preprocessing import image
import numpy as np
import tensorflow as tf
from keras.models import load_model
import keras.backend as K
# Create your views here.

out_dict = {'Average': 0,
            'Bad': 1,
            'Excellent': 2,
            'Good': 3,
            'Worst': 4,
            }

li = list(out_dict.keys())

def index(request):
    if request.method == 'POST':
        if 'myfile' not in request.FILES:
            return HttpResponseRedirect(reverse('seed_app:index'))
        elif request.FILES['myfile']:
            myfile = request.FILES['myfile']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            m = str(filename)
            K.clear_session()
            im = Image.open("{}/".format(settings.MEDIA_ROOT) + m)
            j = im.resize((256, 256),)
            l = "predicted.jpg"
            j.save("{}/".format(settings.MEDIA_ROOT) + l)
            file_url = fs.url(l)
            mod = load_model('seed_app/model.hdf5', compile=False)
            img = image.load_img(myfile, target_size=(32, 32))
            x = image.img_to_array(img)
            x = np.expand_dims(x, axis=0)
            preds = mod.predict(x)
            d = preds.flatten()
            j = d.max()
            for index, item in enumerate(d):
                if item == j:
                    result = li[index]
                    return render(request, "index.html", {
                                    'result': result, 'file_url': file_url })
    return render(request, "index.html")


def seedinfo(request):
    return render(request, 'seedinfo.html')


def gallery(request):
    return render(request, 'gallery.html')

def aboutus(request):
    return render(request, 'aboutus.html')


def upload(request):
    return render(request, 'index1.html')

seed_app/templates/aboutus.html
<!DOCTYPE html>
<style>
    html {
    box-sizing: border-box;
}

*,
*:before,
*:after {
    box-sizing: inherit;
}

.column {
    float: left;
    width: 26.3%;
    margin-bottom: 16px;
    padding: 0 8px;
}

@media screen and (max-width: 650px) {
    .column {
        width: 100%;
        display: block;
    }
}

.card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}

.container {
    padding: 0 16px;
}

.container::after,
.row::after {
    content: "";
    clear: both;
    display: table;
}

.title {
    color: grey;
}

.button {
    border: none;
    outline: 0;
    display: inline-block;
    padding: 8px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
}

.button:hover {
    background-color: #555;
}

</style>
{% extends 'base.html' %}
{% block title %}About Us{% endblock %}
{% load static %}
{% block body_block %}
    <br><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="column">
            <div class="card">
                <img src="{% static 'images/jabeen.jpg' %}" alt="Jabeen" style="width:100%; height:400px;">
                <div class="container">
                    <h2>Jabeen Shrestha</h2>
                  
                    
                    <p>jabeenshrestha@gmail.com</p>
                   
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
        <div class="column">
            <div class="card">
                <img src="{% static 'images/manish.jpg' %}" alt="Manish" style="width:100%; height:400px;">
                <div class="container">
                    <h2>Manish Bhurtel</h2>
                 
                    
                    <p>manish.bhurtel09@gmail.com</p>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="column">
            <div class="card">
                <img src="{% static 'images/niten.jpg' %}" alt="Jane" style="width:100%; height:400px;">
                <div class="container">
                    <div class="container">
                        <h2>Niten Lama</h2>

                 
                        <p>nitenlama46@gmail.com</p>
                        <p></p>
                 
                    </div>
            </div>
        </div>
    </div>
        <div class="col-md-2"></div>
        <div class="column">
            <div class="card">
                <img src="{% static 'images/sajan.jpg' %}" alt="Mike" style="width:100%;height:400px;">
                <div class="container">
                        <h2>Sajan Bhattarai</h2>
                        

                        <p>sajanbhatte@gmail.com</p>
               
                    </div>
            </div>
        </div>
    </div>
   {% endblock %}

seed_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styleeeee.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="container">
    
        <div class="header-bar-warp d-flex">
    
            <h3 style='color: white; font-family: Pacifico, cursive;font-size:26px;'><a style="color: white;"
                    href="{% url 'seed_app:index' %}">Seed Quality Tester</a></h3>
    
            <nav class="top-nav-area w-75">
    
                <!-- Menu -->
                <ul class="main-menu primary-menu">
                    <li><a href="{% url 'seed_app:index' %}"><strong>Home</strong></a></li>
                    <li><a href="{% url 'seed_app:seedinfo' %}"><strong>Seed Info</strong></a></li>
                    <li><a href="{% url 'seed_app:gallery' %}"><strong>Gallery</strong></a></li>
                    <li><a href="{% url 'seed_app:aboutus' %}"><strong>About Us</strong></a></li>
    
                </ul>
                <img style="position: absolute; padding: 8px 10px 0 0; width: 85px; height:85px; display: block; left: 77%; top: 1%; z-index: 1;"
                    src="https://res.cloudinary.com/jabeenstha/image/upload/v1561002772/sqa_oza4ke.png">
            </nav>
    
    
        </div>
    </div>


    

        {% block body_block %}

        {% endblock %}

seed_app/templates/gallery.html
<!DOCTYPE html>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr {
        background-color: #dddddd;
    }
</style>
{% extends 'base.html' %}
{% block title %}Gallery{% endblock %}
{% block body_block %}
    <br><br>
    <div class="container">
    <p style="color:white; font-size:150%;">Maize is a general crop that is cultivated extensively during summer (April
        - August) in the
        Terai and the Hilly
        region of Nepal. As it is the most significant crop in the context of Nepal, the farmer and the general people
        must be aware about all the aspects of Maize seed i.e. the type of maize seed to sow, the time for the maize
        plant to grow completely, location and region to be cultivated, etc.
        As per the research made on 2013 by National Maize Research Program, Rampur, Chitwan under Nepal Agricultural
        Research Council, following fruitful statiscics can be obtained:
    </p>
    </div>
    <br><br>
    <div class="container">
    <table>
        <tr>
            <th>SN</th>
            <th>Registered Maize Varieties</th>
            <th>Year of Release</th>
            <th>Yield Potential Mt/ha</th>
            <th>Maturity(Days)</th>
            <th>Recommendation Domain</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Bio-9681, F1</td>
            <td>2010</td>
            <td>6.5-8</td>
            <td>90-110</td>
            <td>Mid Hill Mid Dev.
                Region-summer season
                East Terai winter seaon</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Rajkumar, F1</td>
            <td>2010</td>
            <td>8-9</td>
            <td>100-110</td>
            <td>Mid Hill Mid Dev.
                Region-summer season
                East Terai winter seaon</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Nutan (KH-101), F1</td>
            <td>2010</td>
            <td>6.5-8</td>
            <td>90-92</td>
            <td>Mid Hill Mid Dev.
                Region-summer season</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Super 900 M, F1</td>
            <td>2010</td>
            <td>8-12</td>
            <td>120-160</td>
            <td>Inner Terai-Winter and
                Summer seaon</td>
        </tr>
        <tr>
            <td>5</td>
            <td>DKC 9081</td>
            <td>2011</td>
            <td>10-12</td>
            <td>120-160</td>
            <td>Inner Terai-Winter
                season (kartik-magh)</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Alrounder, F1</td>
            <td>2011</td>
            <td>7-10</td>
            <td>120-160</td>
            <td>Terai-Winter and
                Summer seaon</td>
        </tr>
    </table>
    </div>
<br> <br>
{% endblock %}

seed_app/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}Seed Quality Tester{% endblock %}
      {% block body_block %}
    <br><br><br>
    <br><br>
    <br>
    <br>
    <div class="container">
        <form method="post" id="fileform" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="file-upload">
                <div class="file-select">
                    <div class="file-select-button" id="fileName">
                        <h6>Upload Image</h6>
                    </div>
                    <div class="file-select-name" id="noFile">
                        {% if file_url %}
                        {{ file_url }}
                        {% else %}
                        No Image Uploaded...
                        {% endif %}
                    </div>
                    <input id="chooseFile" type="file" name="myfile">
                </div>
                <br><br>
            </div>
            <br>
            <div class="file-upload-button">
    
    
                <button id="sub" class="btn btn-primary btn-lg" type="submit">Test Quality</button>
    
            </div>
        </form>
    </div>
    <br>
    
    <div class="container">
        <div class="file-upload-button">
    
            {% if file_url %}
            <h2 id='filename'><strong>{{ result }}</strong></h2>
            <br><br><br>
            <img src={{ file_url }}>
            {% else %}
            <br>
            <h2 style="color:white;">No Preview</h2>
            {% endif %}
    
        </div>
    
    </div>
        {% endblock %}

seed_app/templates/seedinfo.html
<!DOCTYPE html>
<style>
    html {
    box-sizing: border-box;
}

*,
*:before,
*:after {
    box-sizing: inherit;
}

.column {
    float: left;
    width: 26.3%;
    margin-bottom: 16px;
    padding: 0 8px;
}

@media screen and (max-width: 650px) {
    .column {
        width: 100%;
        display: block;
    }
}

.card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}

.container {
    padding: 0 16px;
}

.container::after,
.row::after {
    content: "";
    clear: both;
    display: table;
}

.title {
    color: grey;
}

.button {
    border: none;
    outline: 0;
    display: inline-block;
    padding: 8px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
}

.button:hover {
    background-color: #555;
}

</style>
{% extends 'base.html' %}
{% block title %}Seed Info{% endblock %}
{% load static %}

{% block body_block %}
    <br><br>
   <div class="row">
       <div class="col-md-2"></div>
       <div class="column">
           <div class="card">
               <img src="{% static 'images/excellent.jpg' %}" alt="Jabeen" style="width:100%; height:400px;">
               <div class="container">
                   <h2>Excellent Quality</h2>
               </div>
           </div>
       </div>
       <div class="col-md-2"></div>
       <div class="column">
           <div class="card">
               <img src="{% static 'images/good.jpg' %}" alt="Manish" style="width:100%; height:400px;">
               <div class="container">
                   <h2>Good Quality</h2>



               </div>
           </div>
       </div>
   </div>
   <br><br>
   <div class="row">
       <div class="col-md-2"></div>
       <div class="column">
           <div class="card">
               <img src="{% static 'images/average.jpg' %}" alt="Jane" style="width:100%; height:400px;">
               <div class="container">
                   <div class="container">
                       <h2>Average Quality</h2>





                   </div>
               </div>
           </div>
       </div>
       <div class="col-md-2"></div>
       <div class="column">
           <div class="card">
               <img src="{% static 'images/bad.jpg' %}" alt="Mike" style="width:100%;height:400px;">
               <div class="container">
                   <h2>Bad Quality</h2>



               </div>
           </div>
       </div>
   </div>
   <br><br>
   <div class="row">
       <div class="col-md-2"></div>
       <div class="column">
           <div class="card">
               <img src="{% static 'images/worst.jpg' %}" alt="Jabeen" style="width:100%; height:400px;">
               <div class="container">
                   <h2>Worst Quality</h2>




               </div>
           </div>
       </div>
   </div>
   <br><br>
  {% endblock %}